GET http://localhost:8080/tcslibrary/reading-item/pride-and-prejudice_201907/filename/pride-and-prejudice.pdf/page
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ0Y3NsaWJyYXJ5Iiwic3ViIjoiam9obkBzbWl0aC5jb20iLCJhdXRob3JpdGllcyI6IkFETUlOIiwiYXBwX3VzZXJfaWQiOjEsImV4cCI6MTY5MjczNTEyN30.iRmqp-V638XktLtje3Kdb757UC8zC8htKF6Y2peO3Zo



